POST  http://localhost:9000/v2/posts
Content-Type: application/json

{ 
    "url":"https://res.cloudinary.com/dxkxvfo2o/video/upload/v1608169739/video2_mecbdo.mp4",
    "channel":"sorhan123",
    "description":"Sunday night editing in Windows",
    "song":"Kdenlive is great",
    "likes":"222",
    "shares":"123",
    "messages":"992"
}

###
GET http://localhost:9000/v2/posts